{% set name = "prefect-aws" %}
{% set version = "0.4.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prefect_aws-{{ version }}.tar.gz
  sha256: 3bf70e29f593c1dee265b36e30bf9a7dac1116e9a1f9907c3f13fe1f37ef33a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - boto3 >=1.24.53
    - botocore >=1.27.53
    - mypy-boto3-s3 >=1.24.94
    - mypy-boto3-secretsmanager >=1.26.49
    - prefect >=2.16.4
    - tenacity >=8.0.0

test:
  imports:
    - prefect_aws
# Disable `pip check` until `prefect` adds `pip check` support
#  commands:
#    - pip check
#  requires:
#    - pip

about:
  home: https://github.com/PrefectHQ/prefect-aws
  summary: Prefect collection of tasks and subflows to integrate with AWS
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://prefecthq.github.io/prefect-aws/
  dev_url: https://github.com/PrefectHQ/prefect-aws


extra:
  recipe-maintainers:
    - peterbygrave
    - skrsna
    - ahuang11
    - desertaxle
