{% set name = "prefect-aws" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prefect_aws-{{ version }}.tar.gz
  sha256: 5d32b9c1713c5ce07b0c5d50129ec54e0bce73ebcc80df83be72b90976626058

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - boto3 >=1.24.53
    - botocore >=1.27.53
    - mypy-boto3-s3 >=1.24.94
    - mypy-boto3-secretsmanager >=1.26.49
    - prefect >=2.16.4
    - tenacity >=8.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - prefect_aws
# Disable `pip check` until `prefect` adds `pip check` support
#  commands:
#    - pip check
#  requires:
#    - pip

about:
  home: https://github.com/PrefectHQ/prefect-aws
  summary: Prefect collection of tasks and subflows to integrate with AWS
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://prefecthq.github.io/prefect-aws/
  dev_url: https://github.com/PrefectHQ/prefect-aws


extra:
  recipe-maintainers:
    - mikeoconnor0308
    - peterbygrave
    - skrsna
    - ahuang11
    - desertaxle
