{% set name = "prefect-aws" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prefect-aws-{{ version }}.tar.gz
  sha256: 0cf924fc84f46eb012827cab672b3369169ad882edc25ec480d6aa696d1e6e12

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - boto3 >=1.24.53
    - botocore >=1.27.53
    - prefect >=2.6.7

test:
  imports:
    - prefect_aws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PrefectHQ/prefect-aws
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Prefect collection of tasks and subflows to integrate with AWS
  doc_url: https://prefecthq.github.io/prefect-aws/
  dev_url: https://github.com/PrefectHQ/prefect-aws


extra:
  recipe-maintainers:
    - skrsna
    - ahuang11
    - desertaxle
